### ISSUE TITLE
Multiline RegEx using file as input

### ISSUE THREAD

**Issue by bsahane** [ZSendokame/Sendokame-Regular-Expression#2]
Hello @ZSendokame,

Can you please provide Multiline RegEx support using file as input

Example Command
```
python sre.py --regex "^#.*\n^dn.*\n" --file ldap.txt
```
Example Input File
```
$ cat ldap.txt
# extended LDIF
#
# LDAPv3
# base <ou=mx,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: sendmailMTAAliasValue 
#

# mx, example.com
dn: ou=mx,dc=example,dc=com

# abc@example.com, mx, example.com
dn: sendmailMTAKey=abc@example.com,ou=mx,dc=example,dc=com

# abc-list@example.com, mx, example.com
dn: sendmailMTAKey=abc-list@example.com,ou=mx,dc=example,dc=com

# cloud-subscribe, mx, example.com
dn: sendmailMTAKey=cloud-subscribe,ou=mx,dc=example,dc=com
sendmailMTAAliasValue: cloud-subscribe@example.com

# cloud-unsubscribe, mx, example.com
dn: sendmailMTAKey=cloud-unsubscribe,ou=mx,dc=example,dc=com
sendmailMTAAliasValue: cloud-unsubscribe@example.com


```

**Comment by ZSendokame** [comment]
I can make the script to read a file and apply Regex on it, now i'm with other project but i'll try to do it now

**Comment by ZSendokame** [comment]
And there it is!
`python sre.py --file "file.txt" --regex "You're regex."`
I also print all the matches, not print the string and the matches with green background, i found some errors and bugs on consoles where it output weird symbols
https://github.com/ZSendokame/Sendokame-Regular-Expression/commit/ee1de1f23e8c95196b0dcc519f8bf2595415a197
